<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE Library [
        <!ELEMENT Library (Book)*>
        <!ELEMENT Book (Title|Author|Description|Pubdate|Publisher|Cost)*>
        <!ELEMENT Title (#PCDATA)>
        <!ELEMENT Author (#PCDATA)>
        <!ELEMENT Description (#PCDATA)>
        <!ELEMENT Pubdate (#PCDATA)>
        <!ELEMENT Publisher (#PCDATA)>
        <!ELEMENT Cost (#PCDATA)>
        ]>
<Library>
<Book>
    <Title>
        World Book
    </Title>
    <Author>
        Blintz
    </Author>
    <Description>
        Refer to the example shown in the chapter, describing the simple book.
        Complete the definition of the DTD for the book, and then try out a few examples,
        to see that your XML is matching the requirements.
        Try seeding a few errors into the !XML to see how they are reported.
    </Description>
    <Pubdate></Pubdate>
    <Publisher></Publisher>
    <Cost></Cost>
</Book>
</Library>